export enum TransactionsActionTypes {
  SET_TRANSACTIONS = '@@TRANSACTIONS/SET_TRANSACTIONS',

  LOAD_TRANSACTION_STATUS = '@@TRANSACTIONS/LOAD_TRANSACTION_STATUS',
  LOAD_TRANSACTION_STATUS_SUCCESS = '@@TRANSACTIONS/LOAD_TRANSACTION_STATUS_SUCCESS',
  LOAD_TRANSACTION_STATUS_FAILURE = '@@TRANSACTIONS/LOAD_TRANSACTION_STATUS_FAILURE',
}
