export enum AuthActionTypes {
  START_WALLET = '@@AUTH/START_WALLET',
  START_WALLET_SUCCESS = '@@AUTH/START_WALLET_SUCCESS',
  START_WALLET_FAILURE = '@@AUTH/START_WALLET_FAILURE',

  SET_ERROR = '@@AUTH/SET_ERROR',
}
