export enum AuthActionTypes {
  START_WALLET = '@@AUTH/START_WALLET',
  START_WALLET_SUCCESS = '@@AUTH/START_WALLET_SUCCESS',
  START_WALLET_FAILURE = '@@AUTH/START_WALLET_FAILURE',

  SET_SYNCED_WALLET_STATE = '@@AUTH/SET_SYNCED_WALLET_STATE',

  UPDATE_WALLET_SYNC_PROGRESS = '@@AUTH/UPDATE_WALLET_SYNC_PROGRESS',
}
