export enum AuthActionTypes {
  START_WALLET = '@@AUTH/START_WALLET',
  START_WALLET_SUCCESS = '@@AUTH/START_WALLET_SUCCESS',
  START_WALLET_FAILURE = '@@AUTH/START_WALLET_FAILURE',

  SET_SYNCED_WALLET_STATE = '@@AUTH/SET_SYNCED_WALLET_STATE',

  UPDATE_WALLET_SYNC_PROGRESS = '@@AUTH/UPDATE_WALLET_SYNC_PROGRESS',

  UPDATE_SEED_LIST = '@@AUTH/UPDATE_SEED_LIST',
  UPDATE_SEED_LIST_SUCCESS = '@@AUTH/UPDATE_SEED_LIST_SUCCESS',
  UPDATE_SEED_LIST_FAILURE = '@@AUTH/UPDATE_SEED_LIST_FAILURE',

  RESET_RESTORE_STATE = '@@AUTH/RESET_RESTORE_STATE',

  CHECK_IS_ALLOWED_SEED = '@@AUTH/CHECK_IS_ALLOWED_SEED',
  CHECK_IS_ALLOWED_SEED_SUCCESS = '@@AUTH/CHECK_IS_ALLOWED_SEED_SUCCESS',
  CHECK_IS_ALLOWED_SEED_FAILURE = '@@AUTH/CHECK_IS_ALLOWED_SEED_FAILURE',

  SET_SEED_RESULT = '@@AUTH/SET_SEED_RESULT',
}
