export enum WalletActionTypes {
  SET_TOTALS = '@@WALLET/SET_TOTALS',

  SET_ASSETS = '@@WALLET/SET_ASSETS',

  SET_TRANSACTIONS = '@@WALLET/SET_TRANSACTIONS',

  GET_RATE = '@@WALLET/GET_RATE',
  GET_RATE_SUCCESS = '@@WALLET/GET_RATE_SUCCESS',
  GET_RATE_FAILURE = '@@WALLET/GET_RATE_FAILURE',
}
