export enum WalletActionTypes {
  SET_TOTALS = '@@WALLET/SET_TOTALS',

  SET_ASSETS = '@@WALLET/SET_ASSETS',

  SET_TRANSACTIONS = '@@WALLET/SET_TRANSACTIONS',

  GET_RATE = '@@WALLET/GET_RATE',
  GET_RATE_SUCCESS = '@@WALLET/GET_RATE_SUCCESS',
  GET_RATE_FAILURE = '@@WALLET/GET_RATE_FAILURE',

  SET_RECEIVE_AMOUNT = '@@WALLET/SET_RECEIVE_AMOUNT',

  GENERATE_ADDRESS = '@@WALLET/GENERATE_ADDRESS',
  GENERATE_ADDRESS_SUCCESS = '@@WALLET/GENERATE_ADDRESS_SUCCESS',
  GENERATE_ADDRESS_FAILURE = '@@WALLET/GENERATE_ADDRESS_FAILURE',

  RESET_RECEIVE = '@@WALLET/RESET_RECEIVE',
}
