export enum SharedActionTypes {
  NAVIGATE = '@@SHARED/NAVIGATE',
  SET_ERROR = '@@SHARED/SET_ERROR',
  LOCK_WALLET = '@@SHARED/LOCK_WALLET',
  HIDE_BALANCE = '@@SHARED/HIDE_BALANCE',
  UNLOCK_WALLET = '@@SHARED/UNLOCK_WALLET',
  SET_LOCK_STATE = '@@SHARED/SET_LOCK_STATE',
  SYNC_ASSET = '@@SHARED/SYNC_ASSET',
  UNSET_SYNC_ASSET = '@@SHARED/UNSET_SYNC_ASSET',
  SET_IS_LOADING = '@@SHARED/SET_IS_LOADING',
}
