name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn --frozen-lockfile

      - name: Build wallet
        run: yarn build

      - name: Upload build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: Masternet Web-wallet
          path: dist
